### ISSUE TITLE
On click of the Custom gridview elements the listner is not responding

### ISSUE THREAD

**Issue by tanka** [stacktipslab/Android-UI-Tutorials#1]
solition
the focus is taken by the linear Layout of the row_gird.xml
so change it as below.  it will work.
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_marginTop="5dp"
    android:orientation="vertical"
    android:padding="5dp" 
    android:clickable="false"
    android:background="@drawable/grid_color_selector"
    android:focusable="false">

```
<ImageView
    android:id="@+id/image"
    android:layout_width="100dp"
    android:layout_height="100dp" >
</ImageView>

<TextView
    android:id="@+id/text"
    android:layout_width="fill_parent"
    android:layout_height="wrap_content"
    android:layout_marginTop="5dp"
    android:gravity="center"
    android:textSize="12sp" >
</TextView>
```

</LinearLayout>

**Comment by yogeshmadaan100** [comment]
@javatechig  Please review
